---
stages:
- name: BUILD
  inputs:
  - type: git
    branch: master
    service: ${CATALOG_API_REPO}
  triggers:
  - type: commit
  jobs:
  - name: Build
    type: builder
  - name: Unit Tests
    type: tester
    script: |-
      #!/bin/bash
      GRUNTFILE="tests/Gruntfile.js"
      if [ -f $GRUNTFILE ]; then
        npm install -g npm@3.7.2 ### work around default npm 2.1.1 instability
        npm install
        grunt dev-test-cov --no-color -f --gruntfile $GRUNTFILE --base .
      else
        echo "$GRUNTFILE not found."
      fi      
- name: DEV
  inputs:
  - type: job
    stage: BUILD
    job: Build
  triggers:
  - type: stage
  properties:
  - name: CF_APP_NAME
    value: undefined
    type: text
  - name: APP_URL
    value: undefined
    type: text
  jobs:
  - name: Deploy
    type: deployer
    target:
      region_id: ${DEV_REGION_ID}
      organization: ${DEV_ORG_NAME}
      space: ${DEV_SPACE_NAME}
      application: ${CF_APP_NAME}
    script: |
      #!/bin/bash
      cf create-service cloudantNoSQLDB Shared myMicroservicesCloudant
      cf create-service service_discovery free myMicroservicesServiceDiscovery
      # Push app
      export CF_APP_NAME="dev-$CF_APP"
      cf push
      export APP_URL=http://$(cf app $CF_APP_NAME | grep urls: | awk '{print $2}')
      # View logs
      #cf logs "${CF_APP_NAME}" --recent