---
stages:
- name: BUILD
  inputs:
  - type: git
    branch: master
    service: ${ORDERS_REPO}
  triggers:
  - type: commit
  jobs:
  - name: Build
    type: builder
  - name: mavenBuild
    type: maven
    script: |-
      #!/bin/bash
      mvn clean install
      mkdir -p target/defaultServer/apps
      mv manifest.yml target/
      mv server.xml target/defaultServer/
      mv target/*.war target/defaultServer/apps/
- name: DEPLOY
  inputs:
  - type: git
    stage: BUILD
    job: Build
  triggers:
  - type: stage
  properties:
  - name: CF_APP_NAME
    value: ${CF_APP_NAME}
    type: text
  - name: APP_URL
    value: undefined
    type: text
  jobs:
  - name: Deploy
    type: deployer
    target:
      region_id: ${PROD_REGION_ID}
      organization: ${PROD_ORG_NAME}
      space: ${PROD_SPACE_NAME}
      application: ${CF_APP_NAME}
    script: |
      #!/bin/bash
      cf cs elephantsql turtle myMicroservicesSQL
      cf create-service service_discovery free myMicroservicesServiceDiscovery
      cf push -p defaultServer
      # View logs
      #cf logs "${CF_APP_NAME}" --recent
